/**
 * Concatenates every migration in db/migrations into one file that stands up a
 * fresh database from nothing — for a staging Supabase project, a local
 * `supabase start`, or any other empty Postgres.
 *
 * The migrations are goose-annotated, and 18 of 19 carry a `-- +goose Down`
 * section that DROPs what the Up section just created. Nothing here runs goose:
 * Supabase's SQL editor and its migration runner both treat those markers as
 * plain comments and execute the whole file, so the Down halves MUST be cut or
 * the database ends up empty with no error to explain why.
 *
 * Generated rather than hand-maintained so it cannot drift as migrations are
 * added. Re-run it after writing a new migration.
 *
 *   node backend/db/build-schema.mjs            -> writes backend/db/schema.generated.sql
 *   node backend/db/build-schema.mjs --stdout   -> prints instead, for piping
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS = join(HERE, "migrations");
const OUT = join(HERE, "schema.generated.sql");
// The local Supabase stack rebuilds from supabase/migrations on `db reset`, so
// the same baseline is written there too — one source, both consumers, no drift.
const SUPABASE_BASELINE = join(
  HERE, "..", "..", "supabase", "migrations", "00000000000000_baseline.sql"
);

// Filenames are YYYYMMDDHHMMSS_name.sql, so a plain sort is chronological.
const files = readdirSync(MIGRATIONS).filter((f) => f.endsWith(".sql")).sort();

const parts = [
  "-- GENERATED by backend/db/build-schema.mjs — do not edit.",
  "-- Every migration's Up section, in order, with the goose markers and the",
  "-- Down sections removed. Paste into a fresh database's SQL editor.",
  `-- ${files.length} migrations, built ${new Date().toISOString().slice(0, 10)}.`,
  "",
  "-- ======================================================================",
  "-- Extensions (not in any migration — added by the generator)",
  "-- ======================================================================",
  "--",
  "-- No migration creates these. The schema was authored against a hosted",
  "-- Supabase project, where uuid-ossp, pg_trgm and vector are already enabled",
  "-- through the dashboard, so the migrations just assume them. On a fresh",
  "-- database the very first statement — CREATE FUNCTION ... RETURNS",
  "-- extensions.vector — fails with: type \"extensions.vector\" does not exist.",
  "",
  "CREATE SCHEMA IF NOT EXISTS extensions;",
  'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;',
  "CREATE EXTENSION IF NOT EXISTS pg_trgm     WITH SCHEMA extensions;",
  "CREATE EXTENSION IF NOT EXISTS vector      WITH SCHEMA extensions;",
  "",
  "-- The migrations reference these both schema-qualified (extensions.vector,",
  "-- extensions.vector_cosine_ops) and bare (vector(384), uuid_generate_v4(),",
  "-- gin_trgm_ops), so extensions has to be on the search_path while this runs.",
  "SET search_path TO public, extensions;",
  "",
];

let trimmed = 0;
for (const file of files) {
  let sql = readFileSync(join(MIGRATIONS, file), "utf8");

  // Cut the Down section. Without this the file creates each table and then
  // immediately drops it.
  const down = sql.search(/^--\s*\+goose\s+Down\b/im);
  if (down !== -1) {
    sql = sql.slice(0, down);
    trimmed++;
  }

  sql = sql
    .replace(/^--\s*\+goose\s+(Up|StatementBegin|StatementEnd)\b.*$/gim, "")
    .trim();

  if (!sql) continue;

  parts.push(`-- ${"=".repeat(70)}`, `-- ${file}`, `-- ${"=".repeat(70)}`, "", sql, "");
}

const output = parts.join("\n") + "\n";

if (process.argv.includes("--stdout")) {
  process.stdout.write(output);
} else {
  writeFileSync(OUT, output);
  console.log(`${files.length} migrations -> ${OUT}`);

  const supabaseDir = dirname(SUPABASE_BASELINE);
  if (existsSync(join(supabaseDir, "..", "config.toml"))) {
    mkdirSync(supabaseDir, { recursive: true });
    writeFileSync(SUPABASE_BASELINE, output);
    console.log(`${files.length} migrations -> ${SUPABASE_BASELINE}`);
  }

  console.log(`${trimmed} Down sections stripped`);
  console.log(`${output.split("\n").length} lines, ${(output.length / 1024).toFixed(0)} KB`);
}
