-- GENERATED by backend/db/build-schema.mjs — do not edit.
-- Every migration's Up section, in order, with the goose markers and the
-- Down sections removed. Paste into a fresh database's SQL editor.
-- 20 migrations, built 2026-09-19.

-- ======================================================================
-- Extensions (not in any migration — added by the generator)
-- ======================================================================
--
-- No migration creates these. The schema was authored against a hosted
-- Supabase project, where uuid-ossp, pg_trgm and vector are already enabled
-- through the dashboard, so the migrations just assume them. On a fresh
-- database the very first statement — CREATE FUNCTION ... RETURNS
-- extensions.vector — fails with: type "extensions.vector" does not exist.

CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm     WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS vector      WITH SCHEMA extensions;

-- The migrations reference these both schema-qualified (extensions.vector,
-- extensions.vector_cosine_ops) and bare (vector(384), uuid_generate_v4(),
-- gin_trgm_ops), so extensions has to be on the search_path while this runs.
SET search_path TO public, extensions;

-- ======================================================================
-- 20251108093609_initial_schema.sql
-- ======================================================================

-- Functions


CREATE FUNCTION calculate_weighted_embedding(user_id uuid) RETURNS extensions.vector
    LANGUAGE plpgsql
    AS $$
DECLARE
    weighted_sum vector(384);
    total_weight FLOAT;
BEGIN
    WITH weighted_interactions AS (
        -- Posts: weight 3.0
        SELECT 
            array(SELECT unnest(t.embedding::real[]) * 3.0)::vector(384) as weighted_embedding,
            3.0 as weight
        FROM post_tools pt
        JOIN posts p ON pt.post_id = p.id
        JOIN tools t ON pt.tool_id = t.id
        WHERE p.author_id = user_id AND t.embedding IS NOT NULL
        
        UNION ALL
        
        -- Stack: weight 2.5
        SELECT 
            array(SELECT unnest(t.embedding::real[]) * 2.5)::vector(384),
            2.5
        FROM stack_items s
        JOIN tools t ON s.tool_id = t.id
        WHERE s.profile_id = user_id AND t.embedding IS NOT NULL
        
        UNION ALL
        
        -- Watchlist: weight 2.0
        SELECT 
            array(SELECT unnest(t.embedding::real[]) * 2.0)::vector(384),
            2.0
        FROM watchlist_items w
        JOIN tools t ON w.tool_id = t.id
        WHERE w.profile_id = user_id AND t.embedding IS NOT NULL
        
        UNION ALL
        
        -- Stars: weight 1.0
        SELECT 
            array(SELECT unnest(t.embedding::real[]) * 1.0)::vector(384),
            1.0
        FROM post_stars ps
        JOIN post_tools pt ON ps.post_id = pt.post_id
        JOIN tools t ON pt.tool_id = t.id
        WHERE ps.liker_id = user_id AND t.embedding IS NOT NULL
    )
    SELECT 
        SUM(weighted_embedding),
        SUM(weight)
    INTO weighted_sum, total_weight
    FROM weighted_interactions;
    
    -- Normalize by total weight
    IF total_weight > 0 AND weighted_sum IS NOT NULL THEN
        RETURN array(SELECT unnest(weighted_sum::real[]) / total_weight)::vector(384);
    END IF;
    
    RETURN NULL;
END;
$$;



CREATE FUNCTION custom_access_token_hook(event jsonb) RETURNS jsonb
    LANGUAGE plpgsql
    SECURITY DEFINER
    AS $$
  declare
    claims jsonb;
    user_onboarded boolean;
  begin
    -- Check if user has a profile (indicates they completed onboarding)
    select exists(select 1 from public.profiles where id = (event->>'user_id')::uuid) into user_onboarded;

    -- Extract current claims
    claims := event->'claims';

    -- Ensure 'app_metadata' exists
    if jsonb_typeof(claims->'app_metadata') is null then
      claims := jsonb_set(claims, '{app_metadata}', '{}');
    end if;

    -- Set the 'onboarded' field to true or false based on database value
    claims := jsonb_set(claims, '{app_metadata, onboarded}', to_jsonb(user_onboarded));

    -- Update the 'claims' object in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified event
    return event;
  end;
$$;



CREATE FUNCTION recalculate_all_post_embeddings() RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
  post_record RECORD;
  new_embedding vector(384);
  posts_updated INTEGER := 0;
BEGIN
  -- Start explicit transaction block
  BEGIN
    FOR post_record IN
      SELECT DISTINCT p.id
      FROM posts p
      WHERE EXISTS (
        SELECT 1 FROM post_tools pt WHERE pt.post_id = p.id
      )
    LOOP
      -- Calculate the average embedding of all tools and user for this post
      WITH all_embeddings AS (
        SELECT t.embedding
        FROM post_tools pt
        JOIN tools t ON pt.tool_id = t.id
        WHERE pt.post_id = post_record.id 
          AND t.embedding IS NOT NULL
        
        UNION ALL
        
        SELECT p.embedding
        FROM posts po
        JOIN profiles p ON po.author_id = p.id
        WHERE po.id = post_record.id
          AND p.embedding IS NOT NULL
      )
      SELECT 
        CASE 
          WHEN COUNT(*) > 0 THEN
            AVG(embedding)
          ELSE NULL
        END
      INTO new_embedding
      FROM all_embeddings;
      
      -- Update the post with the recalculated embedding
      UPDATE posts 
      SET embedding = new_embedding, updated_at = now()
      WHERE id = post_record.id;
      
      posts_updated := posts_updated + 1;
    END LOOP;
    
    RAISE NOTICE 'Successfully recalculated embeddings for % posts with associated tools', posts_updated;
    
  EXCEPTION
    WHEN OTHERS THEN
      -- Rollback will happen automatically, just re-raise the error
      RAISE NOTICE 'Error during batch embedding update: %', SQLERRM;
      RAISE;
  END;
END;
$$;



CREATE FUNCTION update_content_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.content_vector :=
    setweight(to_tsvector('english', coalesce(NEW.name, '')),         'A') ||
    setweight(to_tsvector('english', coalesce(NEW.name, '')),         'A') ||
    setweight(to_tsvector('english', coalesce(NEW.name, '')),         'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description, '')),  'B') ||
    setweight(to_tsvector('english', coalesce(NEW.content_text, '')), 'C');
  RETURN NEW;
END;
$$;



CREATE FUNCTION update_post_embedding_on_tools_change() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  target_post_id UUID;
  new_embedding vector(384);
BEGIN
  -- Determine which post to update
  IF TG_OP = 'DELETE' THEN
    target_post_id := OLD.post_id;
  ELSE
    target_post_id := NEW.post_id;
  END IF;
  
  -- Calculate the average embedding of all tools and user associated with this post
  WITH all_embeddings AS (
    SELECT t.embedding
    FROM post_tools pt
    JOIN tools t ON pt.tool_id = t.id
    WHERE pt.post_id = target_post_id 
      AND t.embedding IS NOT NULL
    
    UNION ALL
    
    SELECT p.embedding
    FROM posts po
    JOIN profiles p ON po.author_id = p.id
    WHERE po.id = target_post_id
      AND p.embedding IS NOT NULL
  )
  SELECT 
    CASE 
      WHEN COUNT(*) > 0 THEN
        AVG(embedding)
      ELSE NULL
    END
  INTO new_embedding
  FROM all_embeddings;
  
  -- Update the post with the new embedding
  UPDATE posts 
  SET embedding = new_embedding, updated_at = now()
  WHERE id = target_post_id;
  
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$$;



CREATE FUNCTION update_profiles_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.vector :=
    setweight(to_tsvector('simple', coalesce(NEW.username, '')),         'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.username, '')),         'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.username, '')),         'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.display_name, '')),     'B');
  RETURN NEW;
END;
$$;



CREATE FUNCTION update_tool_tickets_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.vector :=
    setweight(to_tsvector('simple', coalesce(NEW.tool_name, '')),        'A') ||
    setweight(to_tsvector('english', coalesce(NEW.tool_description, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.tool_website, '')),      'C');
  RETURN NEW;
END;
$$;



CREATE FUNCTION update_tools_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.vector :=
    setweight(to_tsvector('simple',  coalesce(NEW.name, '')),           'A') ||
    setweight(to_tsvector('simple',  coalesce(NEW.name, '')),           'A') ||
    setweight(to_tsvector('simple',  coalesce(NEW.name, '')),           'A') ||
    setweight(to_tsvector('english', coalesce(NEW.description, '')),    'B');
  RETURN NEW;
END;
$$;



CREATE FUNCTION update_user_embeddings() RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    user_record RECORD;
BEGIN
    FOR user_record IN
        SELECT DISTINCT p.id
        FROM profiles p
        WHERE EXISTS (
            SELECT 1 FROM posts WHERE author_id = p.id
            AND created_at > COALESCE(p.last_embedding_update, '1970-01-01'::timestamptz)
        )
        OR EXISTS (SELECT 1 FROM stack_items WHERE profile_id = p.id)
        OR EXISTS (SELECT 1 FROM watchlist_items WHERE profile_id = p.id)
        OR EXISTS (
            SELECT 1 FROM post_stars ps WHERE ps.liker_id = p.id
        )
    LOOP
        UPDATE profiles
        SET 
            embedding = calculate_weighted_embedding(user_record.id),
            last_embedding_update = NOW()
        WHERE id = user_record.id;
    END LOOP;
END;
$$;



CREATE FUNCTION update_vendors_vector() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.vector :=
    setweight(to_tsvector('simple', coalesce(NEW.name, '')),    'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.name, '')),    'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.name, '')),    'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.website, '')), 'B') ||
    setweight(
      to_tsvector('simple',
        coalesce(NEW.x_profile, '') || ' ' || coalesce(NEW.linkedin_profile, '')
      ),
      'C'
    );
  RETURN NEW;
END;
$$;


CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    vector tsvector,
    embedding vector(384),
    last_embedding_update TIMESTAMPTZ DEFAULT '1970-01-01 00:00:00+00'::TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vendors (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    website TEXT,
    x_profile TEXT,
    linkedin_profile TEXT,
    head_office TEXT,
    year_of_foundation INTEGER,
    vector tsvector
);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL
);

CREATE TABLE tools (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    vendor_id UUID REFERENCES vendors(id) ON DELETE SET NULL,
    vector tsvector,
    embedding vector(384),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    recipient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK(type IN ('follow', 'post_star', 'post_comment')),
    entity_id UUID,
    entity_type TEXT,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    author_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type in ('playbook', 'combo', 'comparison')),
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    content JSONB,
    content_text TEXT,
    content_vector tsvector,
    draft_content JSONB,
    draft_content_text TEXT,
    is_published BOOLEAN,
    embedding vector(384),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_comments(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    commenter_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_medias(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id UUID NOT NULL REFERENCES posts(id),
    file_name TEXT NOT NULL,
    s3_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_slug_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    old_slug VARCHAR(100) NOT NULL,
    current_slug VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(old_slug)
);

CREATE TABLE post_stars(
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    liker_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, liker_id)
);


CREATE TABLE post_tools (
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tool_id)
);

CREATE TABLE tool_tickets (
    id uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4() NOT NULL,
    post_id uuid NOT NULL,
    requested_by uuid NOT NULL,
    tool_name text NOT NULL,
    tool_description text,
    tool_website text,
    status text DEFAULT 'pending'::text NOT NULL,
    resolved_tool_id uuid,
    resolved_by uuid,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    vector tsvector,
    CONSTRAINT tool_tickets_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'resolved'::text, 'rejected'::text])))
);

CREATE TABLE stack_items (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    PRIMARY KEY (profile_id, tool_id)
);

CREATE TABLE tool_categories (
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (tool_id, category_id)
);

CREATE TABLE tool_ticket_categories (
    ticket_id uuid NOT NULL REFERENCES tool_tickets(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (ticket_id, category_id)
);

CREATE TABLE user_follows(
  follower_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  followee_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (follower_id, followee_id)
);

CREATE TABLE watchlist_items (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    PRIMARY KEY (profile_id, tool_id)
);

-- Views

CREATE VIEW posts_with_tools WITH (security_invoker='on') AS
    SELECT p.id,
        p.type,
        p.name,
        p.slug,
        p.description,
        p.updated_at,
        p.author_id,
        p.is_published,
        u.username AS author_username,
        json_agg(json_build_object('id', t.id, 'name', t.name, 'logo_url', t.logo_url)) AS tools
    FROM (((posts p
        JOIN profiles u ON ((p.author_id = u.id)))
        JOIN post_tools pt ON ((p.id = pt.post_id)))
        JOIN tools t ON ((t.id = pt.tool_id)))
    GROUP BY p.id, u.username, p.type, p.name, p.slug, p.description, p.updated_at, p.author_id, p.is_published;

CREATE VIEW posts_with_tools_and_tickets WITH (security_invoker='on') AS
    SELECT p.id,
        p.type,
        p.name,
        p.slug,
        p.description,
        p.updated_at,
        p.author_id,
        p.is_published,
        u.username AS author_username,
        COALESCE(jsonb_agg(jsonb_build_object('id', combined.id, 'name', combined.name, 'logo_url', combined.logo_url, 'is_ticket', combined.is_ticket)), '[]'::jsonb) AS tools
    FROM ((posts p
        JOIN profiles u ON ((p.author_id = u.id)))
        LEFT JOIN ( SELECT pt.post_id,
                (t.id)::text AS id,
                t.name,
                COALESCE(t.logo_url, ''::text) AS logo_url,
                false AS is_ticket
            FROM (post_tools pt
                JOIN tools t ON ((t.id = pt.tool_id)))
            UNION ALL
            SELECT tt.post_id,
                (tt.id)::text AS id,
                tt.tool_name AS name,
                ''::text AS logo_url,
                true AS is_ticket
            FROM tool_tickets tt
            WHERE (tt.status = 'pending'::text)) combined ON ((combined.post_id = p.id)))
    GROUP BY p.id, u.username, p.type, p.name, p.slug, p.description, p.updated_at, p.author_id, p.is_published;


CREATE VIEW tools_with_details WITH (security_invoker='on') AS
    SELECT t.id,
        t.name,
        t.description,
        t.logo_url,
        t.created_at,
        t.updated_at,
        COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', c.id, 'name', c.name)) FILTER (WHERE (c.id IS NOT NULL)), '[]'::jsonb) AS categories,
        jsonb_build_object('id', v.id, 'website', v.website, 'x_profile', v.x_profile, 'linkedin_profile', v.linkedin_profile, 'head_office', v.head_office, 'year_of_foundation', v.year_of_foundation) AS vendor
    FROM (((tools t
        LEFT JOIN tool_categories tc ON ((t.id = tc.tool_id)))
        LEFT JOIN categories c ON ((tc.category_id = c.id)))
        LEFT JOIN vendors v ON ((t.vendor_id = v.id)))
    GROUP BY t.id, t.name, t.description, t.logo_url, t.created_at, t.updated_at, v.id;

-- Indices

CREATE INDEX idx_categories_name_trgm ON categories USING gin (name gin_trgm_ops);

CREATE INDEX idx_post_slug_history_old_slug ON post_slug_history USING btree (old_slug);

CREATE INDEX idx_post_slug_history_post_id ON post_slug_history USING btree (post_id);

CREATE UNIQUE INDEX idx_posts_author_slug ON posts USING btree (author_id, slug);

CREATE INDEX idx_posts_content_vector ON posts USING gin (content_vector);

CREATE INDEX idx_profiles_embedding_cosine ON profiles USING hnsw (embedding extensions.vector_cosine_ops);

CREATE INDEX idx_profiles_vector ON profiles USING gin (vector);

CREATE INDEX idx_tool_tickets_created_at ON tool_tickets USING btree (created_at DESC);

CREATE INDEX idx_tool_tickets_post_id ON tool_tickets USING btree (post_id);

CREATE INDEX idx_tool_tickets_requested_by ON tool_tickets USING btree (requested_by);

CREATE INDEX idx_tool_tickets_resolved_by ON tool_tickets USING btree (resolved_by);

CREATE INDEX idx_tool_tickets_status ON tool_tickets USING btree (status);

CREATE INDEX idx_tool_tickets_tool_name ON tool_tickets USING btree (tool_name);

CREATE INDEX idx_tool_tickets_vector ON tool_tickets USING gin (vector);

CREATE INDEX idx_tools_vector ON tools USING gin (vector);

CREATE INDEX idx_vendors_vector ON vendors USING gin (vector);

CREATE INDEX trgm_idx ON tools USING gin (name gin_trgm_ops);

-- Triggers

CREATE TRIGGER post_tools_embedding_update_trigger AFTER INSERT OR DELETE OR UPDATE ON post_tools FOR EACH ROW EXECUTE FUNCTION update_post_embedding_on_tools_change();

CREATE TRIGGER posts_content_vector_trigger BEFORE INSERT OR UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION update_content_vector();

CREATE TRIGGER profiles_vector_trigger BEFORE INSERT OR UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_profiles_vector();

CREATE TRIGGER tool_tickets_vector_trigger BEFORE INSERT OR UPDATE ON tool_tickets FOR EACH ROW EXECUTE FUNCTION update_tool_tickets_vector();

CREATE TRIGGER tools_vector_trigger BEFORE INSERT OR UPDATE ON tools FOR EACH ROW EXECUTE FUNCTION update_tools_vector();

CREATE TRIGGER vendors_vector_trigger BEFORE INSERT OR UPDATE ON vendors FOR EACH ROW EXECUTE FUNCTION update_vendors_vector();

-- RLS stuff to make supabase happy

CREATE POLICY "Allow auth hook" ON public.profiles FOR SELECT TO supabase_auth_admin USING (true);

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;

ALTER TABLE post_medias ENABLE ROW LEVEL SECURITY;

ALTER TABLE post_slug_history ENABLE ROW LEVEL SECURITY;

ALTER TABLE post_stars ENABLE ROW LEVEL SECURITY;

ALTER TABLE post_tools ENABLE ROW LEVEL SECURITY;

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE stack_items ENABLE ROW LEVEL SECURITY;

ALTER TABLE tool_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE tool_ticket_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE tool_tickets ENABLE ROW LEVEL SECURITY;

ALTER TABLE tools ENABLE ROW LEVEL SECURITY;

ALTER TABLE user_follows ENABLE ROW LEVEL SECURITY;

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

ALTER TABLE watchlist_items ENABLE ROW LEVEL SECURITY;

-- ======================================================================
-- 20251111131341_draft_and_publish_timestamps.sql
-- ======================================================================

ALTER TABLE posts
ADD last_publish TIMESTAMPTZ;

ALTER TABLE posts
ADD last_draft_update TIMESTAMPTZ;

DROP VIEW posts_with_tools;
DROP VIEW posts_with_tools_and_tickets;

CREATE VIEW posts_with_tools WITH (security_invoker='on') AS
    SELECT p.id,
        p.type,
        p.name,
        p.slug,
        p.description,
        p.updated_at,
        p.created_at,
        p.last_draft_update,
        p.last_publish,
        p.author_id,
        p.is_published,
        u.username AS author_username,
        json_agg(json_build_object('id', t.id, 'name', t.name, 'logo_url', t.logo_url)) AS tools
    FROM (((posts p
        JOIN profiles u ON ((p.author_id = u.id)))
        JOIN post_tools pt ON ((p.id = pt.post_id)))
        JOIN tools t ON ((t.id = pt.tool_id)))
    GROUP BY p.id, u.username, p.type, p.name, p.slug, p.description, p.updated_at, p.author_id, p.is_published;

CREATE VIEW posts_with_tools_and_tickets WITH (security_invoker='on') AS
    SELECT p.id,
        p.type,
        p.name,
        p.slug,
        p.description,
        p.updated_at,
        p.created_at,
        p.last_draft_update,
        p.last_publish,
        p.author_id,
        p.is_published,
        u.username AS author_username,
        COALESCE(jsonb_agg(jsonb_build_object('id', combined.id, 'name', combined.name, 'logo_url', combined.logo_url, 'is_ticket', combined.is_ticket)), '[]'::jsonb) AS tools
    FROM ((posts p
        JOIN profiles u ON ((p.author_id = u.id)))
        LEFT JOIN ( SELECT pt.post_id,
                (t.id)::text AS id,
                t.name,
                COALESCE(t.logo_url, ''::text) AS logo_url,
                false AS is_ticket
            FROM (post_tools pt
                JOIN tools t ON ((t.id = pt.tool_id)))
            UNION ALL
            SELECT tt.post_id,
                (tt.id)::text AS id,
                tt.tool_name AS name,
                ''::text AS logo_url,
                true AS is_ticket
            FROM tool_tickets tt
            WHERE (tt.status = 'pending'::text)) combined ON ((combined.post_id = p.id)))
    GROUP BY p.id, u.username, p.type, p.name, p.slug, p.description, p.updated_at, p.author_id, p.is_published;

-- ======================================================================
-- 20251114000000_add_profile_fields.sql
-- ======================================================================

ALTER TABLE profiles
ADD COLUMN bio TEXT,
ADD COLUMN website TEXT;

-- ======================================================================
-- 20251119140534_add_profile_email_hash.sql
-- ======================================================================

ALTER TABLE profiles
ADD COLUMN email_hash TEXT;


CREATE FUNCTION update_profile_email_hash() RETURNS trigger AS $$
DECLARE
    user_email TEXT;
BEGIN
    -- Only update if email actually changed
    IF TG_OP = 'UPDATE' AND OLD.email = NEW.email THEN
        RETURN NEW;
    END IF;

    -- Get email from auth.users
    SELECT email INTO user_email
    FROM auth.users
    WHERE id = NEW.id;

    IF user_email IS NOT NULL THEN
        UPDATE public.profiles
        SET email_hash = encode(digest(lower(trim(user_email)), 'sha256'), 'hex')
        WHERE id = NEW.id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;



CREATE FUNCTION fill_profile_email_hash() RETURNS trigger AS $$
DECLARE
    user_email TEXT;
BEGIN
    -- Get email from auth.users
    SELECT email INTO user_email
    FROM auth.users
    WHERE id = NEW.id;

    IF user_email IS NOT NULL THEN
        NEW.email_hash := encode(digest(lower(trim(user_email)), 'sha256'), 'hex');
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE TRIGGER update_profile_email_hash_trigger
    AFTER INSERT OR UPDATE ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION update_profile_email_hash();

CREATE TRIGGER fill_profile_email_hash_trigger
    BEFORE INSERT ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION fill_profile_email_hash();

-- ======================================================================
-- 20260624120000_key_tools.sql
-- ======================================================================

CREATE TABLE key_tools (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, tool_id)
);

-- ======================================================================
-- 20260624130000_stack_watchlist_added_at.sql
-- ======================================================================

ALTER TABLE stack_items ADD COLUMN added_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE watchlist_items ADD COLUMN added_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- ======================================================================
-- 20260624140000_profile_contact_fields.sql
-- ======================================================================

ALTER TABLE profiles ADD COLUMN company TEXT;
ALTER TABLE profiles ADD COLUMN location TEXT;
ALTER TABLE profiles ADD COLUMN linkedin TEXT;
ALTER TABLE profiles ADD COLUMN twitter TEXT;

-- ======================================================================
-- 20260624150000_key_playbooks.sql
-- ======================================================================

CREATE TABLE key_playbooks (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    position INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_id, post_id)
);

-- ======================================================================
-- 20260630120000_tool_follows.sql
-- ======================================================================

CREATE TABLE tool_follows (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, tool_id)
);

-- ======================================================================
-- 20260710120000_tool_slug_index.sql
-- ======================================================================

-- Functional index backing GetToolIDBySlug. The expression must match the query
-- exactly for the planner to use it.
CREATE INDEX IF NOT EXISTS idx_tools_name_slug
ON tools (btrim(lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')), '-'));

-- ======================================================================
-- 20260712120000_tool_ticket_standalone.sql
-- ======================================================================

-- Allow tool tickets that are not tied to a playbook (standalone "Add tool"
-- suggestions from the /tools browse page).
ALTER TABLE tool_tickets ALTER COLUMN post_id DROP NOT NULL;

-- ======================================================================
-- 20260712130000_case_insensitive_usernames.sql
-- ======================================================================

-- Usernames are case-insensitive: "Max" and "max" must be the same account.
-- Normalize everything that already exists to lowercase.
--
-- NOTE: this fails if two profiles already differ only by case. Check first:
--   SELECT lower(username), count(*) FROM profiles
--   GROUP BY lower(username) HAVING count(*) > 1;
UPDATE profiles SET username = lower(username) WHERE username <> lower(username);

-- Belt-and-braces: even if some code path forgets to normalize, the database
-- refuses two usernames differing only by case.
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_username_lower
ON profiles (lower(username));

-- ======================================================================
-- 20260723120000_tool_approved_notification.sql
-- ======================================================================

-- Allow the new "tool_approved" notification type (sent when an admin resolves
-- a user's tool ticket).
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('follow', 'post_star', 'post_comment', 'tool_approved'));

-- ======================================================================
-- 20260730120000_enable_rls_all_public_tables.sql
-- ======================================================================

-- Enable Row Level Security on every table in the public schema.
--
-- Supabase auto-exposes a REST API for public tables using the public `anon`
-- key (shipped in the browser bundle). Without RLS, anyone with that key can
-- read/write these tables directly, bypassing the Go backend entirely — most
-- critically account_claims, which holds single-use claim tokens (credentials).
--
-- We enable RLS with NO policies: the anon/authenticated roles are denied all
-- access through the REST API, while the Go backend (direct connection as table
-- owner) and service-role scripts continue to bypass RLS and work unchanged.
--
-- ENABLE (not FORCE) is deliberate so the owner/service role keep full access.
do $$
declare r record;
begin
  for r in
    select tablename from pg_tables where schemaname = 'public'
  loop
    execute format('alter table public.%I enable row level security;', r.tablename);
  end loop;
end $$;

-- ======================================================================
-- 20260809120000_old_stack_items.sql
-- ======================================================================

-- Tools a user used to run but no longer actively uses (e.g. HubSpot at a
-- previous company). Mirrors stack_items / watchlist_items. A tool lives in at
-- most one of the three lists; the add handlers enforce that mutual exclusivity.
CREATE TABLE old_stack_items (
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (profile_id, tool_id)
);

ALTER TABLE old_stack_items ENABLE ROW LEVEL SECURITY;

-- ======================================================================
-- 20260809140000_user_follows_created_at.sql
-- ======================================================================

-- The activity feed orders follow events chronologically; user_follows had no
-- timestamp (tool_follows already has added_at). Existing rows collapse to the
-- migration time, which is fine — they simply appear as the oldest events.
ALTER TABLE user_follows ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS user_follows_follower_created_idx
    ON user_follows (follower_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tool_follows_profile_added_idx
    ON tool_follows (profile_id, added_at DESC);

-- ======================================================================
-- 20260809160000_profile_avatar_url.sql
-- ======================================================================

-- Uploaded profile picture. NULL means the user hasn't uploaded one, in which
-- case the UI falls back to their Gravatar (via email_hash), then to initials.
ALTER TABLE profiles ADD COLUMN avatar_url TEXT;

-- ======================================================================
-- 20260809180000_profile_focus_areas.sql
-- ======================================================================

-- GTM focus areas chosen during onboarding ("What's your focus?").
-- These are a curated taxonomy owned by the app, not rows in `categories`
-- (which holds the much more granular vendor-directory categories), so they are
-- stored as plain text keys rather than foreign keys.
ALTER TABLE profiles ADD COLUMN focus_areas TEXT[] NOT NULL DEFAULT '{}';

-- Marks that the user has been through the multi-step onboarding, so the flow
-- is not shown again to people who already have a profile.
ALTER TABLE profiles ADD COLUMN onboarding_completed_at TIMESTAMPTZ;

-- ======================================================================
-- 20260912120000_tool_page_ownership.sql
-- ======================================================================

-- Vendor-side ownership of a tool page. Several people from the same company
-- may own one tool, and one person may own several, so this is a join table
-- rather than a column on tools. Ownership is granted by hand once a claim
-- submitted through the "Claim this page" form has been verified — there is
-- deliberately no HTTP endpoint that grants it.
CREATE TABLE tool_owners (
    tool_id UUID NOT NULL REFERENCES tools(id) ON DELETE CASCADE,
    profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    granted_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tool_id, profile_id)
);

-- "Which tools does this person own?" for profile pages and the claim script.
CREATE INDEX idx_tool_owners_profile ON tool_owners (profile_id);

ALTER TABLE tool_owners ENABLE ROW LEVEL SECURITY;

-- Owner-written page copy, stored as Tiptap JSON — the same editor playbooks
-- use. tools.description stays a plain-text projection of it, so search,
-- embeddings and the catalogue cards keep working untouched.
ALTER TABLE tools ADD COLUMN description_rich TEXT;

-- Appending a column is all CREATE OR REPLACE VIEW allows; the existing ones
-- keep their names, types and order. t.id is the primary key, so the extra
-- column is functionally dependent on the GROUP BY and needs no entry there.
CREATE OR REPLACE VIEW tools_with_details WITH (security_invoker='on') AS
    SELECT t.id,
        t.name,
        t.description,
        t.logo_url,
        t.created_at,
        t.updated_at,
        COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', c.id, 'name', c.name)) FILTER (WHERE (c.id IS NOT NULL)), '[]'::jsonb) AS categories,
        jsonb_build_object('id', v.id, 'website', v.website, 'x_profile', v.x_profile, 'linkedin_profile', v.linkedin_profile, 'head_office', v.head_office, 'year_of_foundation', v.year_of_foundation) AS vendor,
        t.description_rich
    FROM (((tools t
        LEFT JOIN tool_categories tc ON ((t.id = tc.tool_id)))
        LEFT JOIN categories c ON ((tc.category_id = c.id)))
        LEFT JOIN vendors v ON ((t.vendor_id = v.id)))
    GROUP BY t.id, t.name, t.description, t.logo_url, t.created_at, t.updated_at, v.id;

-- ======================================================================
-- 20260919210000_pin_email_hash_function_search_path.sql
-- ======================================================================

-- update_profile_email_hash() and fill_profile_email_hash() are SECURITY
-- DEFINER but pin no search_path, so they resolve `digest()` and
-- `public.profiles` against whatever search_path the *caller* happens to have.
--
-- update_profile_email_hash() is a trigger on auth.users, so its caller is
-- GoTrue, connecting as supabase_auth_admin — whose search_path is `auth`
-- alone. `digest()` lives in the extensions schema, which is not on that path,
-- so every user creation fails with:
--
--   function digest(text, unknown) does not exist (SQLSTATE 42883)
--
-- This never surfaced in production only because that database's roles happen
-- to be configured with extensions on the path. Relying on that is fragile —
-- and for a SECURITY DEFINER function it is also the classic search_path
-- injection weakness, since a caller controls which schema an unqualified name
-- resolves to while the body runs with the definer's privileges.
--
-- Pinning the path fixes both. No function body changes, so this is safe to
-- apply to a database where these functions already exist.

ALTER FUNCTION update_profile_email_hash()
    SET search_path = public, extensions, pg_temp;

ALTER FUNCTION fill_profile_email_hash()
    SET search_path = public, extensions, pg_temp;

