// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddPostTools implements pgx.CopyFromSource.
type iteratorForAddPostTools struct {
	rows                 []AddPostToolsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddPostTools) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddPostTools) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PostID,
		r.rows[0].ToolID,
	}, nil
}

func (r iteratorForAddPostTools) Err() error {
	return nil
}

func (q *Queries) AddPostTools(ctx context.Context, arg []AddPostToolsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"post_tools"}, []string{"post_id", "tool_id"}, &iteratorForAddPostTools{rows: arg})
}

// iteratorForAddToolTicketCategories implements pgx.CopyFromSource.
type iteratorForAddToolTicketCategories struct {
	rows                 []AddToolTicketCategoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddToolTicketCategories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddToolTicketCategories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TicketID,
		r.rows[0].CategoryID,
	}, nil
}

func (r iteratorForAddToolTicketCategories) Err() error {
	return nil
}

func (q *Queries) AddToolTicketCategories(ctx context.Context, arg []AddToolTicketCategoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tool_ticket_categories"}, []string{"ticket_id", "category_id"}, &iteratorForAddToolTicketCategories{rows: arg})
}
