// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type Notification struct {
	ID          uuid.UUID          `json:"id"`
	RecipientID uuid.UUID          `json:"recipient_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	Type        string             `json:"type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	EntityType  pgtype.Text        `json:"entity_type"`
	Title       string             `json:"title"`
	Message     string             `json:"message"`
	IsRead      pgtype.Bool        `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID               uuid.UUID          `json:"id"`
	AuthorID         uuid.UUID          `json:"author_id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Description      string             `json:"description"`
	Content          []byte             `json:"content"`
	ContentText      pgtype.Text        `json:"content_text"`
	ContentVector    interface{}        `json:"content_vector"`
	DraftContent     []byte             `json:"draft_content"`
	DraftContentText pgtype.Text        `json:"draft_content_text"`
	IsPublished      pgtype.Bool        `json:"is_published"`
	Embedding        interface{}        `json:"embedding"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastPublish      pgtype.Timestamptz `json:"last_publish"`
	LastDraftUpdate  pgtype.Timestamptz `json:"last_draft_update"`
}

type PostComment struct {
	ID          uuid.UUID          `json:"id"`
	PostID      uuid.UUID          `json:"post_id"`
	CommenterID uuid.UUID          `json:"commenter_id"`
	Content     string             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PostMedia struct {
	ID        uuid.UUID          `json:"id"`
	PostID    uuid.UUID          `json:"post_id"`
	FileName  string             `json:"file_name"`
	S3Key     string             `json:"s3_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostSlugHistory struct {
	ID          uuid.UUID          `json:"id"`
	PostID      uuid.UUID          `json:"post_id"`
	OldSlug     string             `json:"old_slug"`
	CurrentSlug string             `json:"current_slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PostStar struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

type PostTool struct {
	PostID uuid.UUID `json:"post_id"`
	ToolID uuid.UUID `json:"tool_id"`
}

type PostsWithTool struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           json.RawMessage    `json:"tools"`
}

type PostsWithToolsAndTicket struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           interface{}        `json:"tools"`
}

type Profile struct {
	ID                  uuid.UUID          `json:"id"`
	DisplayName         string             `json:"display_name"`
	Username            string             `json:"username"`
	Vector              interface{}        `json:"vector"`
	Embedding           interface{}        `json:"embedding"`
	LastEmbeddingUpdate pgtype.Timestamptz `json:"last_embedding_update"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Bio                 pgtype.Text        `json:"bio"`
	Website             pgtype.Text        `json:"website"`
	EmailHash           pgtype.Text        `json:"email_hash"`
}

type StackItem struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}

type Tool struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	VendorID    pgtype.UUID        `json:"vendor_id"`
	Vector      interface{}        `json:"vector"`
	Embedding   interface{}        `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ToolCategory struct {
	ToolID     uuid.UUID `json:"tool_id"`
	CategoryID int32     `json:"category_id"`
}

type ToolTicket struct {
	ID              uuid.UUID          `json:"id"`
	PostID          uuid.UUID          `json:"post_id"`
	RequestedBy     uuid.UUID          `json:"requested_by"`
	ToolName        string             `json:"tool_name"`
	ToolDescription pgtype.Text        `json:"tool_description"`
	ToolWebsite     pgtype.Text        `json:"tool_website"`
	Status          string             `json:"status"`
	ResolvedToolID  pgtype.UUID        `json:"resolved_tool_id"`
	ResolvedBy      pgtype.UUID        `json:"resolved_by"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Vector          interface{}        `json:"vector"`
}

type ToolTicketCategory struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	CategoryID int32     `json:"category_id"`
}

type ToolsWithDetail struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      json.RawMessage    `json:"vendor"`
}

type UserFollow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

type Vendor struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Website          pgtype.Text `json:"website"`
	XProfile         pgtype.Text `json:"x_profile"`
	LinkedinProfile  pgtype.Text `json:"linkedin_profile"`
	HeadOffice       pgtype.Text `json:"head_office"`
	YearOfFoundation pgtype.Int4 `json:"year_of_foundation"`
	Vector           interface{} `json:"vector"`
}

type WatchlistItem struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}
