// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPostToolSafe = `-- name: AddPostToolSafe :exec
INSERT INTO post_tools (post_id, tool_id)
VALUES ($1, $2)
ON CONFLICT (post_id, tool_id) DO NOTHING
`

type AddPostToolSafeParams struct {
	PostID uuid.UUID `json:"post_id"`
	ToolID uuid.UUID `json:"tool_id"`
}

func (q *Queries) AddPostToolSafe(ctx context.Context, arg AddPostToolSafeParams) error {
	_, err := q.db.Exec(ctx, addPostToolSafe, arg.PostID, arg.ToolID)
	return err
}

type AddPostToolsParams struct {
	PostID uuid.UUID `json:"post_id"`
	ToolID uuid.UUID `json:"tool_id"`
}

const addToStack = `-- name: AddToStack :exec
INSERT INTO stack_items (profile_id, tool_id)
VALUES ($1, $2)
ON CONFLICT (profile_id, tool_id) DO NOTHING
`

type AddToStackParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}

func (q *Queries) AddToStack(ctx context.Context, arg AddToStackParams) error {
	_, err := q.db.Exec(ctx, addToStack, arg.ProfileID, arg.ToolID)
	return err
}

const addToWatchlist = `-- name: AddToWatchlist :exec
INSERT INTO watchlist_items (profile_id, tool_id)
VALUES ($1, $2)
ON CONFLICT (profile_id, tool_id) DO NOTHING
`

type AddToWatchlistParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) error {
	_, err := q.db.Exec(ctx, addToWatchlist, arg.ProfileID, arg.ToolID)
	return err
}

type AddToolTicketCategoriesParams struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	CategoryID int32     `json:"category_id"`
}

const assignCategoryToTool = `-- name: AssignCategoryToTool :exec
INSERT INTO tool_categories (
  tool_id, category_id
) VALUES (
  $1, $2
)
`

type AssignCategoryToToolParams struct {
	ToolID     uuid.UUID `json:"tool_id"`
	CategoryID int32     `json:"category_id"`
}

func (q *Queries) AssignCategoryToTool(ctx context.Context, arg AssignCategoryToToolParams) error {
	_, err := q.db.Exec(ctx, assignCategoryToTool, arg.ToolID, arg.CategoryID)
	return err
}

const autocompleteCategory = `-- name: AutocompleteCategory :many
SELECT
  id,
  name,
  slug,
  similarity(name, $1) AS rank
FROM
  categories
WHERE
  name % $1 OR name ILIKE $1 || '%'
ORDER BY
  rank DESC, name ASC
LIMIT $2
`

type AutocompleteCategoryParams struct {
	Similarity interface{} `json:"similarity"`
	Limit      int32       `json:"limit"`
}

type AutocompleteCategoryRow struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
	Rank interface{} `json:"rank"`
}

func (q *Queries) AutocompleteCategory(ctx context.Context, arg AutocompleteCategoryParams) ([]AutocompleteCategoryRow, error) {
	rows, err := q.db.Query(ctx, autocompleteCategory, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutocompleteCategoryRow
	for rows.Next() {
		var i AutocompleteCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const autocompleteTool = `-- name: AutocompleteTool :many
SELECT id, name, description, logo_url, similarity(name, $1) AS sml
FROM tools
WHERE name % $1 OR name ILIKE $1 || '%'
ORDER BY
  CASE
    WHEN LOWER(name) = LOWER($1) THEN 0           -- exact match first
    WHEN LOWER(name) LIKE LOWER($1) || '%' THEN 1 -- prefix match second
    ELSE 2
  END,
  sml DESC,
  name
LIMIT $2
`

type AutocompleteToolParams struct {
	Similarity interface{} `json:"similarity"`
	Limit      int32       `json:"limit"`
}

type AutocompleteToolRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	Sml         interface{} `json:"sml"`
}

func (q *Queries) AutocompleteTool(ctx context.Context, arg AutocompleteToolParams) ([]AutocompleteToolRow, error) {
	rows, err := q.db.Query(ctx, autocompleteTool, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutocompleteToolRow
	for rows.Next() {
		var i AutocompleteToolRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.Sml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkUsernameAvailable = `-- name: CheckUsernameAvailable :one
SELECT COUNT(*) = 0 as available
FROM profiles
WHERE username = $1
`

func (q *Queries) CheckUsernameAvailable(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameAvailable, username)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const createCategoryIfNotExist = `-- name: CreateCategoryIfNotExist :one
INSERT INTO categories (
  name
) VALUES (
  $1
)
ON CONFLICT(name) DO UPDATE
SET name = categories.name
RETURNING id, name, slug
`

func (q *Queries) CreateCategoryIfNotExist(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategoryIfNotExist, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (recipient_id, actor_id, type, entity_id, entity_type, title, message)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE NOT EXISTS (
  SELECT 1 FROM notifications 
  WHERE recipient_id = $1 
  AND actor_id = $2 
  AND type = $3 
  AND entity_id = $4
  AND created_at > NOW() - INTERVAL '1 hour'
)
`

type CreateNotificationParams struct {
	RecipientID uuid.UUID   `json:"recipient_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	Type        string      `json:"type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	EntityType  pgtype.Text `json:"entity_type"`
	Title       string      `json:"title"`
	Message     string      `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.RecipientID,
		arg.ActorID,
		arg.Type,
		arg.EntityID,
		arg.EntityType,
		arg.Title,
		arg.Message,
	)
	return err
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (
  author_id, type, name, slug, description
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, slug
`

type CreatePostParams struct {
	AuthorID    uuid.UUID `json:"author_id"`
	Type        string    `json:"type"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
}

type CreatePostRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// FIXME
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Type,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i CreatePostRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createPostComment = `-- name: CreatePostComment :exec
INSERT INTO post_comments (post_id, commenter_id, content)
VALUES ($1, $2, $3)
`

type CreatePostCommentParams struct {
	PostID      uuid.UUID `json:"post_id"`
	CommenterID uuid.UUID `json:"commenter_id"`
	Content     string    `json:"content"`
}

func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) error {
	_, err := q.db.Exec(ctx, createPostComment, arg.PostID, arg.CommenterID, arg.Content)
	return err
}

const createPostMedia = `-- name: CreatePostMedia :exec
INSERT INTO post_medias (post_id, file_name, s3_key)
VALUES ($1, $2, $3)
`

type CreatePostMediaParams struct {
	PostID   uuid.UUID `json:"post_id"`
	FileName string    `json:"file_name"`
	S3Key    string    `json:"s3_key"`
}

func (q *Queries) CreatePostMedia(ctx context.Context, arg CreatePostMediaParams) error {
	_, err := q.db.Exec(ctx, createPostMedia, arg.PostID, arg.FileName, arg.S3Key)
	return err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
  id,
  username,
  display_name
) VALUES (
  $1, $2, $3
) RETURNING id, username, display_name
`

type CreateProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

type CreateProfileRow struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.ID, arg.Username, arg.DisplayName)
	var i CreateProfileRow
	err := row.Scan(&i.ID, &i.Username, &i.DisplayName)
	return i, err
}

const createTool = `-- name: CreateTool :one
INSERT INTO tools (
  name, description, logo_url
) VALUES (
  $1, $2, $3
)
RETURNING id, name, description, logo_url
`

type CreateToolParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

type CreateToolRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (CreateToolRow, error) {
	row := q.db.QueryRow(ctx, createTool, arg.Name, arg.Description, arg.LogoUrl)
	var i CreateToolRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
	)
	return i, err
}

const createToolTicket = `-- name: CreateToolTicket :one
INSERT INTO tool_tickets (
  post_id, requested_by, tool_name, tool_description, tool_website
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id
`

type CreateToolTicketParams struct {
	PostID          uuid.UUID   `json:"post_id"`
	RequestedBy     uuid.UUID   `json:"requested_by"`
	ToolName        string      `json:"tool_name"`
	ToolDescription pgtype.Text `json:"tool_description"`
	ToolWebsite     pgtype.Text `json:"tool_website"`
}

func (q *Queries) CreateToolTicket(ctx context.Context, arg CreateToolTicketParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createToolTicket,
		arg.PostID,
		arg.RequestedBy,
		arg.ToolName,
		arg.ToolDescription,
		arg.ToolWebsite,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications 
WHERE id = $1 AND recipient_id = $2
`

type DeleteNotificationParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.RecipientID)
	return err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts
WHERE id = $1 AND author_id = $2
`

type DeletePostParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editPostComment = `-- name: EditPostComment :exec
UPDATE post_comments
SET content = $2,
    updated_at = now()
WHERE id = $1 AND commenter_id = $2
`

type EditPostCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) EditPostComment(ctx context.Context, arg EditPostCommentParams) error {
	_, err := q.db.Exec(ctx, editPostComment, arg.ID, arg.Content)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO user_follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT (follower_id, followee_id) DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug
FROM categories
WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getFacetCounts = `-- name: GetFacetCounts :one
WITH
  query AS (
    SELECT websearch_to_tsquery('english', $1) q
  )
SELECT
  (SELECT COUNT(*) FROM posts, query WHERE posts.content_vector @@ query.q AND posts.is_published = true) AS post_count,
  (SELECT COUNT(*) FROM tools, query WHERE tools.vector @@ query.q) AS tool_count,
  (SELECT COUNT(*) FROM profiles, query WHERE profiles.vector @@ query.q) AS profile_count
`

type GetFacetCountsRow struct {
	PostCount    int64 `json:"post_count"`
	ToolCount    int64 `json:"tool_count"`
	ProfileCount int64 `json:"profile_count"`
}

func (q *Queries) GetFacetCounts(ctx context.Context, websearchToTsquery string) (GetFacetCountsRow, error) {
	row := q.db.QueryRow(ctx, getFacetCounts, websearchToTsquery)
	var i GetFacetCountsRow
	err := row.Scan(&i.PostCount, &i.ToolCount, &i.ProfileCount)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, type, name, slug, description, updated_at, created_at, last_draft_update, last_publish, author_id, is_published, author_username, tools
FROM posts_with_tools_and_tickets
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (PostsWithToolsAndTicket, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i PostsWithToolsAndTicket
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.LastDraftUpdate,
		&i.LastPublish,
		&i.AuthorID,
		&i.IsPublished,
		&i.AuthorUsername,
		&i.Tools,
	)
	return i, err
}

const getPostContent = `-- name: GetPostContent :one
SELECT id, content FROM posts
WHERE id = $1 LIMIT 1
`

type GetPostContentRow struct {
	ID      uuid.UUID `json:"id"`
	Content []byte    `json:"content"`
}

func (q *Queries) GetPostContent(ctx context.Context, id uuid.UUID) (GetPostContentRow, error) {
	row := q.db.QueryRow(ctx, getPostContent, id)
	var i GetPostContentRow
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}

const getPostDraftContent = `-- name: GetPostDraftContent :one
SELECT id, draft_content FROM posts
WHERE id = $1 AND author_id = $2 LIMIT 1
`

type GetPostDraftContentParams struct {
	ID              uuid.UUID `json:"id"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
}

type GetPostDraftContentRow struct {
	ID           uuid.UUID `json:"id"`
	DraftContent []byte    `json:"draft_content"`
}

func (q *Queries) GetPostDraftContent(ctx context.Context, arg GetPostDraftContentParams) (GetPostDraftContentRow, error) {
	row := q.db.QueryRow(ctx, getPostDraftContent, arg.ID, arg.AuthenticatedID)
	var i GetPostDraftContentRow
	err := row.Scan(&i.ID, &i.DraftContent)
	return i, err
}

const getPostMetadataForUser = `-- name: GetPostMetadataForUser :one
SELECT 
  EXISTS(SELECT 1 FROM post_stars WHERE post_id = $1 AND liker_id = $2) AS is_starred
`

type GetPostMetadataForUserParams struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) GetPostMetadataForUser(ctx context.Context, arg GetPostMetadataForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getPostMetadataForUser, arg.PostID, arg.LikerID)
	var is_starred bool
	err := row.Scan(&is_starred)
	return is_starred, err
}

const getProfile = `-- name: GetProfile :one
SELECT
  id,
  username,
  display_name,
  bio,
  website,
  email_hash,
  created_at,
  updated_at
FROM
  public.profiles
WHERE
  id = $1
`

type GetProfileRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	Bio         pgtype.Text        `json:"bio"`
	Website     pgtype.Text        `json:"website"`
	EmailHash   pgtype.Text        `json:"email_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.EmailHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileWithUsername = `-- name: GetProfileWithUsername :one
SELECT
  id,
  username,
  display_name,
  bio,
  website,
  email_hash,
  created_at,
  updated_at
FROM
  profiles
WHERE
  username = $1
`

type GetProfileWithUsernameRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	Bio         pgtype.Text        `json:"bio"`
	Website     pgtype.Text        `json:"website"`
	EmailHash   pgtype.Text        `json:"email_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProfileWithUsername(ctx context.Context, username string) (GetProfileWithUsernameRow, error) {
	row := q.db.QueryRow(ctx, getProfileWithUsername, username)
	var i GetProfileWithUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.Website,
		&i.EmailHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTool = `-- name: GetTool :one
SELECT id, name, description, logo_url, created_at, updated_at, categories, vendor
FROM tools_with_details
WHERE id = $1
`

func (q *Queries) GetTool(ctx context.Context, id uuid.UUID) (ToolsWithDetail, error) {
	row := q.db.QueryRow(ctx, getTool, id)
	var i ToolsWithDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Categories,
		&i.Vendor,
	)
	return i, err
}

const getToolAuthenticated = `-- name: GetToolAuthenticated :one
SELECT
  id, name, description, logo_url, created_at, updated_at, categories, vendor,
  -- User status
  EXISTS(SELECT 1 FROM stack_items si WHERE si.profile_id = $2 AND si.tool_id = twd.id) AS is_in_stack,
  EXISTS(SELECT 1 FROM watchlist_items wi WHERE wi.profile_id = $2 AND wi.tool_id = twd.id) AS is_in_watchlist
FROM tools_with_details twd
WHERE id = $1
`

type GetToolAuthenticatedParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

type GetToolAuthenticatedRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Categories    interface{}        `json:"categories"`
	Vendor        json.RawMessage    `json:"vendor"`
	IsInStack     bool               `json:"is_in_stack"`
	IsInWatchlist bool               `json:"is_in_watchlist"`
}

func (q *Queries) GetToolAuthenticated(ctx context.Context, arg GetToolAuthenticatedParams) (GetToolAuthenticatedRow, error) {
	row := q.db.QueryRow(ctx, getToolAuthenticated, arg.ID, arg.ProfileID)
	var i GetToolAuthenticatedRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Categories,
		&i.Vendor,
		&i.IsInStack,
		&i.IsInWatchlist,
	)
	return i, err
}

const getToolFromTicket = `-- name: GetToolFromTicket :one
SELECT
  tt.tool_name AS name,
  tt.tool_description AS description,
  '' AS logo_url,
  tt.created_at,
  tt.created_at AS updated_at,
  -- Aggregate categories into JSON array from ticket categories
  COALESCE(
    jsonb_agg(
      DISTINCT jsonb_build_object(
        'id', c.id,
        'name', c.name
      )
    ) FILTER (WHERE c.id IS NOT NULL),
    '[]'::jsonb
  ) AS categories,
  -- No vendor for ticket tools
  NULL AS vendor
FROM
  tool_tickets tt
LEFT JOIN
  tool_ticket_categories ttc ON tt.id = ttc.ticket_id
LEFT JOIN
  categories c ON ttc.category_id = c.id
WHERE
  tt.id = $1
GROUP BY
  tt.id, tt.tool_name, tt.tool_description, tt.created_at
`

type GetToolFromTicketRow struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     string             `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      interface{}        `json:"vendor"`
}

func (q *Queries) GetToolFromTicket(ctx context.Context, id uuid.UUID) (GetToolFromTicketRow, error) {
	row := q.db.QueryRow(ctx, getToolFromTicket, id)
	var i GetToolFromTicketRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Categories,
		&i.Vendor,
	)
	return i, err
}

const getToolTicket = `-- name: GetToolTicket :one
SELECT
  tt.id,
  tt.post_id,
  tt.requested_by,
  tt.tool_name,
  tt.tool_description,
  tt.tool_website,
  tt.status,
  tt.resolved_tool_id,
  tt.resolved_by,
  tt.resolved_at,
  tt.created_at,
  tt.updated_at,
  p.name AS post_name,
  p.slug AS post_slug,
  requester.username AS requester_username,
  resolver.username AS resolver_username,
  COALESCE(
    json_agg(
      DISTINCT jsonb_build_object(
        'id', c.id,
        'name', c.name
      )
    ) FILTER (WHERE c.id IS NOT NULL),
    '[]'
  ) AS categories
FROM
  tool_tickets tt
JOIN
  posts p ON tt.post_id = p.id
JOIN
  profiles requester ON tt.requested_by = requester.id
LEFT JOIN
  profiles resolver ON tt.resolved_by = resolver.id
LEFT JOIN
  tool_ticket_categories ttc ON tt.id = ttc.ticket_id
LEFT JOIN
  categories c ON ttc.category_id = c.id
WHERE
  tt.id = $1
GROUP BY
  tt.id, p.name, p.slug, requester.username, resolver.username
`

type GetToolTicketRow struct {
	ID                uuid.UUID          `json:"id"`
	PostID            uuid.UUID          `json:"post_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	ToolName          string             `json:"tool_name"`
	ToolDescription   pgtype.Text        `json:"tool_description"`
	ToolWebsite       pgtype.Text        `json:"tool_website"`
	Status            string             `json:"status"`
	ResolvedToolID    pgtype.UUID        `json:"resolved_tool_id"`
	ResolvedBy        pgtype.UUID        `json:"resolved_by"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PostName          string             `json:"post_name"`
	PostSlug          string             `json:"post_slug"`
	RequesterUsername string             `json:"requester_username"`
	ResolverUsername  pgtype.Text        `json:"resolver_username"`
	Categories        interface{}        `json:"categories"`
}

func (q *Queries) GetToolTicket(ctx context.Context, id uuid.UUID) (GetToolTicketRow, error) {
	row := q.db.QueryRow(ctx, getToolTicket, id)
	var i GetToolTicketRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.RequestedBy,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolWebsite,
		&i.Status,
		&i.ResolvedToolID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostName,
		&i.PostSlug,
		&i.RequesterUsername,
		&i.ResolverUsername,
		&i.Categories,
	)
	return i, err
}

const getToolsByCategory = `-- name: GetToolsByCategory :many
SELECT
  id, name, description, logo_url, created_at, updated_at, categories, vendor,
  COUNT(*) OVER() AS total_count
FROM tools_with_details twd
WHERE EXISTS (
  SELECT 1 
  FROM tool_categories tc2 
  JOIN categories c2 ON tc2.category_id = c2.id 
  WHERE tc2.tool_id = twd.id AND c2.slug = $1
)
ORDER BY name
LIMIT $2 OFFSET $3
`

type GetToolsByCategoryParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetToolsByCategoryRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      json.RawMessage    `json:"vendor"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) GetToolsByCategory(ctx context.Context, arg GetToolsByCategoryParams) ([]GetToolsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getToolsByCategory, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetToolsByCategoryRow
	for rows.Next() {
		var i GetToolsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStack = `-- name: ListUserStack :many
SELECT
  twd.id, twd.name, twd.description, twd.logo_url, twd.created_at, twd.updated_at, twd.categories, twd.vendor
FROM tools_with_details twd
JOIN stack_items si ON si.tool_id = twd.id
JOIN profiles p ON p.id = si.profile_id
WHERE p.username = $1
ORDER BY twd.name
`

type ListUserStackRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      json.RawMessage    `json:"vendor"`
}

func (q *Queries) ListUserStack(ctx context.Context, username string) ([]ListUserStackRow, error) {
	rows, err := q.db.Query(ctx, listUserStack, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserStackRow
	for rows.Next() {
		var i ListUserStackRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWatchlist = `-- name: ListUserWatchlist :many
SELECT
  twd.id, twd.name, twd.description, twd.logo_url, twd.created_at, twd.updated_at, twd.categories, twd.vendor
FROM tools_with_details twd
JOIN watchlist_items wi ON wi.tool_id = twd.id
JOIN profiles p ON p.id = wi.profile_id
WHERE p.username = $1
ORDER BY twd.name
`

type ListUserWatchlistRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      json.RawMessage    `json:"vendor"`
}

func (q *Queries) ListUserWatchlist(ctx context.Context, username string) ([]ListUserWatchlistRow, error) {
	rows, err := q.db.Query(ctx, listUserWatchlist, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserWatchlistRow
	for rows.Next() {
		var i ListUserWatchlistRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserKeyTools = `-- name: ListUserKeyTools :many
SELECT
  twd.id, twd.name, twd.description, twd.logo_url, twd.created_at, twd.updated_at, twd.categories, twd.vendor
FROM tools_with_details twd
JOIN key_tools kt ON kt.tool_id = twd.id
JOIN profiles p ON p.id = kt.profile_id
WHERE p.username = $1
ORDER BY kt.position
`

type ListUserKeyToolsRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Categories  interface{}        `json:"categories"`
	Vendor      json.RawMessage    `json:"vendor"`
}

func (q *Queries) ListUserKeyTools(ctx context.Context, username string) ([]ListUserKeyToolsRow, error) {
	rows, err := q.db.Query(ctx, listUserKeyTools, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserKeyToolsRow
	for rows.Next() {
		var i ListUserKeyToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllKeyTools = `-- name: RemoveAllKeyTools :exec
DELETE FROM key_tools
WHERE profile_id = $1
`

func (q *Queries) RemoveAllKeyTools(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllKeyTools, profileID)
	return err
}

const addKeyTool = `-- name: AddKeyTool :exec
INSERT INTO key_tools (profile_id, tool_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (profile_id, tool_id) DO UPDATE SET position = EXCLUDED.position
`

type AddKeyToolParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
	Position  int32     `json:"position"`
}

func (q *Queries) AddKeyTool(ctx context.Context, arg AddKeyToolParams) error {
	_, err := q.db.Exec(ctx, addKeyTool, arg.ProfileID, arg.ToolID, arg.Position)
	return err
}

const getTopCategories = `-- name: GetTopCategories :many
SELECT 
  c.id,
  c.name,
  c.slug,
  COUNT(tc.tool_id) AS tool_count
FROM 
  categories c
LEFT JOIN 
  tool_categories tc ON c.id = tc.category_id
GROUP BY 
  c.id, c.name, c.slug
HAVING 
  COUNT(tc.tool_id) > 0
ORDER BY 
  tool_count DESC, c.name ASC
LIMIT $1
`

type GetTopCategoriesRow struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	ToolCount int64  `json:"tool_count"`
}

func (q *Queries) GetTopCategories(ctx context.Context, limit int32) ([]GetTopCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getTopCategories, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCategoriesRow
	for rows.Next() {
		var i GetTopCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ToolCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPosts = `-- name: GetTopPosts :many
SELECT id, type, name, slug, description, updated_at, created_at, last_draft_update, last_publish, author_id, is_published, author_username, tools
FROM posts_with_tools
WHERE is_published
ORDER BY updated_at DESC
LIMIT $1
`

func (q *Queries) GetTopPosts(ctx context.Context, limit int32) ([]PostsWithTool, error) {
	rows, err := q.db.Query(ctx, getTopPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostsWithTool
	for rows.Next() {
		var i PostsWithTool
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.LastDraftUpdate,
			&i.LastPublish,
			&i.AuthorID,
			&i.IsPublished,
			&i.AuthorUsername,
			&i.Tools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRecommendedPosts = `-- name: GetTopRecommendedPosts :many
WITH user_embedding AS (
  SELECT embedding FROM profiles WHERE id = $1
)
SELECT
  pwt.id, pwt.type, pwt.name, pwt.slug, pwt.description, pwt.updated_at, pwt.created_at, pwt.last_draft_update, pwt.last_publish, pwt.author_id, pwt.is_published, pwt.author_username, pwt.tools,
  (1 - (user_embedding.embedding <=> p.embedding))::REAL AS cosine_similarity,
  $3::boolean AND EXISTS(SELECT 1 FROM post_stars ps WHERE ps.post_id = pwt.id AND ps.liker_id = $1) AS is_starred
FROM
  posts_with_tools_and_tickets pwt
  JOIN posts p ON pwt.id = p.id,
  user_embedding
WHERE
  p.embedding IS NOT NULL 
  AND user_embedding.embedding IS NOT NULL
  AND p.is_published = true
  AND p.author_id != $1
  AND NOT EXISTS (
    SELECT 1 FROM post_stars ps 
    WHERE ps.post_id = p.id AND ps.liker_id = $1
  )
ORDER BY
  cosine_similarity DESC
LIMIT $2
`

type GetTopRecommendedPostsParams struct {
	LikerID         uuid.UUID `json:"liker_id"`
	Limit           int32     `json:"limit"`
	IsAuthenticated bool      `json:"is_authenticated"`
}

type GetTopRecommendedPostsRow struct {
	ID               uuid.UUID          `json:"id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Description      string             `json:"description"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate  pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish      pgtype.Timestamptz `json:"last_publish"`
	AuthorID         uuid.UUID          `json:"author_id"`
	IsPublished      pgtype.Bool        `json:"is_published"`
	AuthorUsername   string             `json:"author_username"`
	Tools            interface{}        `json:"tools"`
	CosineSimilarity float32            `json:"cosine_similarity"`
	IsStarred        pgtype.Bool        `json:"is_starred"`
}

func (q *Queries) GetTopRecommendedPosts(ctx context.Context, arg GetTopRecommendedPostsParams) ([]GetTopRecommendedPostsRow, error) {
	rows, err := q.db.Query(ctx, getTopRecommendedPosts, arg.LikerID, arg.Limit, arg.IsAuthenticated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRecommendedPostsRow
	for rows.Next() {
		var i GetTopRecommendedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.LastDraftUpdate,
			&i.LastPublish,
			&i.AuthorID,
			&i.IsPublished,
			&i.AuthorUsername,
			&i.Tools,
			&i.CosineSimilarity,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRecommendedTools = `-- name: GetTopRecommendedTools :many
WITH user_embedding AS (
  SELECT embedding FROM profiles WHERE id = $1
)
SELECT
  twd.id, twd.name, twd.description, twd.logo_url, twd.created_at, twd.updated_at, twd.categories, twd.vendor,
  (1 - (user_embedding.embedding <=> t.embedding))::REAL AS cosine_similarity
FROM
  tools_with_details twd
  JOIN tools t ON twd.id = t.id,
  user_embedding
WHERE
  t.embedding IS NOT NULL 
  AND user_embedding.embedding IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM stack_items si
    WHERE si.profile_id = $1 AND si.tool_id = t.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM watchlist_items wi
    WHERE wi.profile_id = $1 AND wi.tool_id = t.id
  )
ORDER BY
  cosine_similarity DESC
LIMIT $2
`

type GetTopRecommendedToolsParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

type GetTopRecommendedToolsRow struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	LogoUrl          pgtype.Text        `json:"logo_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Categories       interface{}        `json:"categories"`
	Vendor           json.RawMessage    `json:"vendor"`
	CosineSimilarity float32            `json:"cosine_similarity"`
}

func (q *Queries) GetTopRecommendedTools(ctx context.Context, arg GetTopRecommendedToolsParams) ([]GetTopRecommendedToolsRow, error) {
	rows, err := q.db.Query(ctx, getTopRecommendedTools, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRecommendedToolsRow
	for rows.Next() {
		var i GetTopRecommendedToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
			&i.CosineSimilarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRecommendedUsers = `-- name: GetTopRecommendedUsers :many
WITH user_embedding AS (
  SELECT embedding FROM profiles WHERE id = $1
)
SELECT
  p.id,
  p.username,
  p.display_name,
  (1 - (user_embedding.embedding <=> p.embedding))::REAL AS cosine_similarity,
  COALESCE(
    (SELECT COUNT(*) 
     FROM posts 
     WHERE author_id = p.id 
     AND is_published = true), 
    0
  )::INTEGER AS post_count
FROM
  profiles p,
  user_embedding
WHERE
  p.id != $1 
  AND p.embedding IS NOT NULL 
  AND user_embedding.embedding IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM user_follows 
    WHERE follower_id = $1 AND followee_id = p.id
  )
ORDER BY
  cosine_similarity DESC
LIMIT $2
`

type GetTopRecommendedUsersParams struct {
	ID    uuid.UUID `json:"id"`
	Limit int32     `json:"limit"`
}

type GetTopRecommendedUsersRow struct {
	ID               uuid.UUID `json:"id"`
	Username         string    `json:"username"`
	DisplayName      string    `json:"display_name"`
	CosineSimilarity float32   `json:"cosine_similarity"`
	PostCount        int32     `json:"post_count"`
}

func (q *Queries) GetTopRecommendedUsers(ctx context.Context, arg GetTopRecommendedUsersParams) ([]GetTopRecommendedUsersRow, error) {
	rows, err := q.db.Query(ctx, getTopRecommendedUsers, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRecommendedUsersRow
	for rows.Next() {
		var i GetTopRecommendedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.CosineSimilarity,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)::INTEGER as count
FROM notifications 
WHERE recipient_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, recipientID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, recipientID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT 
  n.id,
  n.recipient_id,
  n.actor_id,
  n.type,
  n.entity_id,
  n.entity_type,
  n.title,
  n.message,
  n.is_read,
  n.created_at,
  actor.username as actor_username,
  actor.display_name as actor_display_name
FROM notifications n
LEFT JOIN profiles actor ON n.actor_id = actor.id
WHERE n.recipient_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	RecipientID uuid.UUID `json:"recipient_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type GetUserNotificationsRow struct {
	ID               uuid.UUID          `json:"id"`
	RecipientID      uuid.UUID          `json:"recipient_id"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	Type             string             `json:"type"`
	EntityID         pgtype.UUID        `json:"entity_id"`
	EntityType       pgtype.Text        `json:"entity_type"`
	Title            string             `json:"title"`
	Message          string             `json:"message"`
	IsRead           pgtype.Bool        `json:"is_read"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActorUsername    pgtype.Text        `json:"actor_username"`
	ActorDisplayName pgtype.Text        `json:"actor_display_name"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]GetUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNotificationsRow
	for rows.Next() {
		var i GetUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.ActorID,
			&i.Type,
			&i.EntityID,
			&i.EntityType,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.ActorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPost = `-- name: GetUserPost :one
SELECT 
  id, type, name, slug, description, updated_at, created_at, last_draft_update, last_publish, author_id, is_published, author_username, tools,
  $3::boolean AND EXISTS(SELECT 1 FROM post_stars ps WHERE ps.post_id = pwt.id AND ps.liker_id = $4) AS is_starred
FROM posts_with_tools_and_tickets pwt
WHERE author_username = $1 AND slug = $2 AND (($3::boolean AND author_id = $4) OR is_published)
`

type GetUserPostParams struct {
	AuthorUsername  string    `json:"author_username"`
	Slug            string    `json:"slug"`
	IsAuthenticated bool      `json:"is_authenticated"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
}

type GetUserPostRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           interface{}        `json:"tools"`
	IsStarred       pgtype.Bool        `json:"is_starred"`
}

func (q *Queries) GetUserPost(ctx context.Context, arg GetUserPostParams) (GetUserPostRow, error) {
	row := q.db.QueryRow(ctx, getUserPost,
		arg.AuthorUsername,
		arg.Slug,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
	)
	var i GetUserPostRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.LastDraftUpdate,
		&i.LastPublish,
		&i.AuthorID,
		&i.IsPublished,
		&i.AuthorUsername,
		&i.Tools,
		&i.IsStarred,
	)
	return i, err
}

const getUserPostByOldSlug = `-- name: GetUserPostByOldSlug :one
SELECT 
  p.id, p.type, p.name, p.slug, p.description, p.updated_at, p.created_at, p.last_draft_update, p.last_publish, p.author_id, p.is_published, p.author_username, p.tools,
  $3::boolean AND EXISTS(SELECT 1 FROM post_stars ps WHERE ps.post_id = p.id AND ps.liker_id = $4) AS is_starred
FROM post_slug_history h
JOIN posts_with_tools_and_tickets p ON h.post_id = p.id
WHERE h.old_slug = $1 AND p.author_username = $2
  AND (($3::boolean AND p.author_id = $4) OR p.is_published)
`

type GetUserPostByOldSlugParams struct {
	OldSlug         string    `json:"old_slug"`
	AuthorUsername  string    `json:"author_username"`
	IsAuthenticated bool      `json:"is_authenticated"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
}

type GetUserPostByOldSlugRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           interface{}        `json:"tools"`
	IsStarred       pgtype.Bool        `json:"is_starred"`
}

func (q *Queries) GetUserPostByOldSlug(ctx context.Context, arg GetUserPostByOldSlugParams) (GetUserPostByOldSlugRow, error) {
	row := q.db.QueryRow(ctx, getUserPostByOldSlug,
		arg.OldSlug,
		arg.AuthorUsername,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
	)
	var i GetUserPostByOldSlugRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.LastDraftUpdate,
		&i.LastPublish,
		&i.AuthorID,
		&i.IsPublished,
		&i.AuthorUsername,
		&i.Tools,
		&i.IsStarred,
	)
	return i, err
}

const getUserPostDirect = `-- name: GetUserPostDirect :one
SELECT 
  id, type, name, slug, description, updated_at, created_at, last_draft_update, last_publish, author_id, is_published, author_username, tools,
  $3::boolean AND EXISTS(SELECT 1 FROM post_stars ps WHERE ps.post_id = pwt.id AND ps.liker_id = $4) AS is_starred
FROM posts_with_tools_and_tickets pwt
WHERE author_username = $1 AND slug = $2 AND (($3::boolean AND author_id = $4) OR is_published)
`

type GetUserPostDirectParams struct {
	AuthorUsername  string    `json:"author_username"`
	Slug            string    `json:"slug"`
	IsAuthenticated bool      `json:"is_authenticated"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
}

type GetUserPostDirectRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           interface{}        `json:"tools"`
	IsStarred       pgtype.Bool        `json:"is_starred"`
}

func (q *Queries) GetUserPostDirect(ctx context.Context, arg GetUserPostDirectParams) (GetUserPostDirectRow, error) {
	row := q.db.QueryRow(ctx, getUserPostDirect,
		arg.AuthorUsername,
		arg.Slug,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
	)
	var i GetUserPostDirectRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.LastDraftUpdate,
		&i.LastPublish,
		&i.AuthorID,
		&i.IsPublished,
		&i.AuthorUsername,
		&i.Tools,
		&i.IsStarred,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
  SELECT 1 FROM user_follows 
  WHERE follower_id = $1 AND followee_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const listPostComments = `-- name: ListPostComments :many
SELECT c.id, c.commenter_id, c.content, c.created_at FROM post_comments c
JOIN posts p ON c.post_id = p.id
WHERE c.post_id = $1 AND (($2::boolean = true AND p.author_id = $3) OR p.is_published)
`

type ListPostCommentsParams struct {
	PostID          uuid.UUID `json:"post_id"`
	IsAuthenticated bool      `json:"is_authenticated"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
}

type ListPostCommentsRow struct {
	ID          uuid.UUID          `json:"id"`
	CommenterID uuid.UUID          `json:"commenter_id"`
	Content     string             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPostComments(ctx context.Context, arg ListPostCommentsParams) ([]ListPostCommentsRow, error) {
	rows, err := q.db.Query(ctx, listPostComments, arg.PostID, arg.IsAuthenticated, arg.AuthenticatedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsRow
	for rows.Next() {
		var i ListPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommenterID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, name, description FROM posts
ORDER BY name
LIMIT 5
`

type ListPostsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) ListPosts(ctx context.Context) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolTickets = `-- name: ListToolTickets :many
SELECT
  tt.id,
  tt.post_id,
  tt.requested_by,
  tt.tool_name,
  tt.tool_description,
  tt.tool_website,
  tt.status,
  tt.resolved_tool_id,
  tt.resolved_by,
  tt.resolved_at,
  tt.created_at,
  tt.updated_at,
  p.name AS post_name,
  p.slug AS post_slug,
  requester.username AS requester_username,
  resolver.username AS resolver_username,
  COALESCE(
    jsonb_agg(
      DISTINCT jsonb_build_object(
        'id', c.id,
        'name', c.name
      )
    ) FILTER (WHERE c.id IS NOT NULL),
    '[]'::jsonb
  ) AS categories,
  COUNT(*) OVER() AS total_count
FROM
  tool_tickets tt
JOIN
  posts p ON tt.post_id = p.id
JOIN
  profiles requester ON tt.requested_by = requester.id
LEFT JOIN
  profiles resolver ON tt.resolved_by = resolver.id
LEFT JOIN
  tool_ticket_categories ttc ON tt.id = ttc.ticket_id
LEFT JOIN
  categories c ON ttc.category_id = c.id
WHERE
  ($1::text = '' OR tt.status = $1::text)
GROUP BY
  tt.id, p.name, p.slug, requester.username, resolver.username
ORDER BY
  tt.created_at DESC
LIMIT $2 OFFSET $3
`

type ListToolTicketsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListToolTicketsRow struct {
	ID                uuid.UUID          `json:"id"`
	PostID            uuid.UUID          `json:"post_id"`
	RequestedBy       uuid.UUID          `json:"requested_by"`
	ToolName          string             `json:"tool_name"`
	ToolDescription   pgtype.Text        `json:"tool_description"`
	ToolWebsite       pgtype.Text        `json:"tool_website"`
	Status            string             `json:"status"`
	ResolvedToolID    pgtype.UUID        `json:"resolved_tool_id"`
	ResolvedBy        pgtype.UUID        `json:"resolved_by"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PostName          string             `json:"post_name"`
	PostSlug          string             `json:"post_slug"`
	RequesterUsername string             `json:"requester_username"`
	ResolverUsername  pgtype.Text        `json:"resolver_username"`
	Categories        interface{}        `json:"categories"`
	TotalCount        int64              `json:"total_count"`
}

func (q *Queries) ListToolTickets(ctx context.Context, arg ListToolTicketsParams) ([]ListToolTicketsRow, error) {
	rows, err := q.db.Query(ctx, listToolTickets, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToolTicketsRow
	for rows.Next() {
		var i ListToolTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.RequestedBy,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolWebsite,
			&i.Status,
			&i.ResolvedToolID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PostName,
			&i.PostSlug,
			&i.RequesterUsername,
			&i.ResolverUsername,
			&i.Categories,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPosts = `-- name: ListUserPosts :many
SELECT 
  id, type, name, slug, description, updated_at, created_at, last_draft_update, last_publish, author_id, is_published, author_username, tools,
  COUNT(*) OVER() AS total_count
FROM posts_with_tools
WHERE
  author_username = $1 AND (($4::boolean = true AND author_id = $5) OR is_published)
  AND ($6::boolean = false OR type = $7)
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListUserPostsParams struct {
	AuthorUsername  string    `json:"author_username"`
	Limit           int32     `json:"limit"`
	Offset          int32     `json:"offset"`
	IsAuthenticated bool      `json:"is_authenticated"`
	AuthenticatedID uuid.UUID `json:"authenticated_id"`
	UsePostFilter   bool      `json:"use_post_filter"`
	PostFilter      string    `json:"post_filter"`
}

type ListUserPostsRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           json.RawMessage    `json:"tools"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) ListUserPosts(ctx context.Context, arg ListUserPostsParams) ([]ListUserPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserPosts,
		arg.AuthorUsername,
		arg.Limit,
		arg.Offset,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
		arg.UsePostFilter,
		arg.PostFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPostsRow
	for rows.Next() {
		var i ListUserPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.LastDraftUpdate,
			&i.LastPublish,
			&i.AuthorID,
			&i.IsPublished,
			&i.AuthorUsername,
			&i.Tools,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStarredPosts = `-- name: ListUserStarredPosts :many
SELECT 
  pwt.id, pwt.type, pwt.name, pwt.slug, pwt.description, pwt.updated_at, pwt.created_at, pwt.last_draft_update, pwt.last_publish, pwt.author_id, pwt.is_published, pwt.author_username, pwt.tools,
  COUNT(*) OVER() AS total_count
FROM posts_with_tools pwt
JOIN post_stars ps ON pwt.id = ps.post_id
WHERE ps.liker_id = $1 AND pwt.is_published
ORDER BY pwt.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListUserStarredPostsParams struct {
	LikerID uuid.UUID `json:"liker_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListUserStarredPostsRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           json.RawMessage    `json:"tools"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) ListUserStarredPosts(ctx context.Context, arg ListUserStarredPostsParams) ([]ListUserStarredPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserStarredPosts, arg.LikerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserStarredPostsRow
	for rows.Next() {
		var i ListUserStarredPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.LastDraftUpdate,
			&i.LastPublish,
			&i.AuthorID,
			&i.IsPublished,
			&i.AuthorUsername,
			&i.Tools,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications 
SET is_read = true 
WHERE recipient_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, recipientID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications 
SET is_read = true 
WHERE id = $1 AND recipient_id = $2
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	return err
}

const publishPost = `-- name: PublishPost :exec
UPDATE posts
SET content = draft_content, content_text = draft_content_text, is_published = true, updated_at = now(), last_publish = now()
WHERE id = $1 AND author_id = $2
`

type PublishPostParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) error {
	_, err := q.db.Exec(ctx, publishPost, arg.ID, arg.AuthorID)
	return err
}

const rejectToolTicket = `-- name: RejectToolTicket :exec
UPDATE tool_tickets
SET
  status = 'rejected',
  resolved_by = $2,
  resolved_at = now(),
  updated_at = now()
WHERE id = $1
`

type RejectToolTicketParams struct {
	ID         uuid.UUID   `json:"id"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) RejectToolTicket(ctx context.Context, arg RejectToolTicketParams) error {
	_, err := q.db.Exec(ctx, rejectToolTicket, arg.ID, arg.ResolvedBy)
	return err
}

const removeFromStack = `-- name: RemoveFromStack :exec
DELETE FROM stack_items 
WHERE profile_id = $1 AND tool_id = $2
`

type RemoveFromStackParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}

func (q *Queries) RemoveFromStack(ctx context.Context, arg RemoveFromStackParams) error {
	_, err := q.db.Exec(ctx, removeFromStack, arg.ProfileID, arg.ToolID)
	return err
}

const removeFromWatchlist = `-- name: RemoveFromWatchlist :exec
DELETE FROM watchlist_items 
WHERE profile_id = $1 AND tool_id = $2
`

type RemoveFromWatchlistParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	ToolID    uuid.UUID `json:"tool_id"`
}

func (q *Queries) RemoveFromWatchlist(ctx context.Context, arg RemoveFromWatchlistParams) error {
	_, err := q.db.Exec(ctx, removeFromWatchlist, arg.ProfileID, arg.ToolID)
	return err
}

const removePostComment = `-- name: RemovePostComment :exec
DELETE FROM post_comments
WHERE id = $1 AND commenter_id = $2
`

type RemovePostCommentParams struct {
	ID          uuid.UUID `json:"id"`
	CommenterID uuid.UUID `json:"commenter_id"`
}

func (q *Queries) RemovePostComment(ctx context.Context, arg RemovePostCommentParams) error {
	_, err := q.db.Exec(ctx, removePostComment, arg.ID, arg.CommenterID)
	return err
}

const renamePostWithSlugHistory = `-- name: RenamePostWithSlugHistory :exec
WITH old_post AS (
  SELECT p.id, p.slug, p.author_id
  FROM posts p
  WHERE p.id = $1 AND p.author_id = $2
),
post_update AS (
  UPDATE posts 
  SET name = $3, slug = $4, description = $5, updated_at = now()
  WHERE id = $1 AND author_id = $2
  RETURNING id, slug
),
history_insert AS (
  INSERT INTO post_slug_history (post_id, old_slug, current_slug)
  SELECT old_post.id, old_post.slug, post_update.slug
  FROM old_post, post_update
  WHERE old_post.slug != post_update.slug
  RETURNING post_id
)
UPDATE post_slug_history AS h
SET current_slug = $4
WHERE h.post_id = $1 AND h.current_slug != $4
`

type RenamePostWithSlugHistoryParams struct {
	PostID      uuid.UUID `json:"post_id"`
	AuthorID    uuid.UUID `json:"author_id"`
	Name        string    `json:"name"`
	CurrentSlug string    `json:"current_slug"`
	Description string    `json:"description"`
}

func (q *Queries) RenamePostWithSlugHistory(ctx context.Context, arg RenamePostWithSlugHistoryParams) error {
	_, err := q.db.Exec(ctx, renamePostWithSlugHistory,
		arg.PostID,
		arg.AuthorID,
		arg.Name,
		arg.CurrentSlug,
		arg.Description,
	)
	return err
}

const resolveToolTicketWithExisting = `-- name: ResolveToolTicketWithExisting :exec
UPDATE tool_tickets
SET
  status = 'resolved',
  resolved_tool_id = $2,
  resolved_by = $3,
  resolved_at = now(),
  updated_at = now()
WHERE id = $1
`

type ResolveToolTicketWithExistingParams struct {
	ID             uuid.UUID   `json:"id"`
	ResolvedToolID pgtype.UUID `json:"resolved_tool_id"`
	ResolvedBy     pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveToolTicketWithExisting(ctx context.Context, arg ResolveToolTicketWithExistingParams) error {
	_, err := q.db.Exec(ctx, resolveToolTicketWithExisting, arg.ID, arg.ResolvedToolID, arg.ResolvedBy)
	return err
}

const resolveToolTicketWithNew = `-- name: ResolveToolTicketWithNew :exec
UPDATE tool_tickets
SET
  status = 'resolved',
  resolved_tool_id = $2,
  resolved_by = $3,
  resolved_at = now(),
  updated_at = now()
WHERE id = $1
`

type ResolveToolTicketWithNewParams struct {
	ID             uuid.UUID   `json:"id"`
	ResolvedToolID pgtype.UUID `json:"resolved_tool_id"`
	ResolvedBy     pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveToolTicketWithNew(ctx context.Context, arg ResolveToolTicketWithNewParams) error {
	_, err := q.db.Exec(ctx, resolveToolTicketWithNew, arg.ID, arg.ResolvedToolID, arg.ResolvedBy)
	return err
}

const saveDraftAndPublishPost = `-- name: SaveDraftAndPublishPost :execrows
UPDATE posts
SET draft_content = $2, draft_content_text = $3, content = $2, content_text = $3, is_published = true, updated_at = now(), last_publish = now(), last_draft_update = now()
WHERE id = $1 AND author_id = $4
`

type SaveDraftAndPublishPostParams struct {
	ID               uuid.UUID   `json:"id"`
	DraftContent     []byte      `json:"draft_content"`
	DraftContentText pgtype.Text `json:"draft_content_text"`
	AuthorID         uuid.UUID   `json:"author_id"`
}

func (q *Queries) SaveDraftAndPublishPost(ctx context.Context, arg SaveDraftAndPublishPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveDraftAndPublishPost,
		arg.ID,
		arg.DraftContent,
		arg.DraftContentText,
		arg.AuthorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const savePostDraft = `-- name: SavePostDraft :execrows
UPDATE posts
SET draft_content = $2, draft_content_text = $3, updated_at = now(), last_draft_update = now()
WHERE id = $1 AND author_id = $4
`

type SavePostDraftParams struct {
	ID               uuid.UUID   `json:"id"`
	DraftContent     []byte      `json:"draft_content"`
	DraftContentText pgtype.Text `json:"draft_content_text"`
	AuthorID         uuid.UUID   `json:"author_id"`
}

func (q *Queries) SavePostDraft(ctx context.Context, arg SavePostDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePostDraft,
		arg.ID,
		arg.DraftContent,
		arg.DraftContentText,
		arg.AuthorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchPost = `-- name: SearchPost :many
SELECT 
  pwt.id, pwt.type, pwt.name, pwt.slug, pwt.description, pwt.updated_at, pwt.created_at, pwt.last_draft_update, pwt.last_publish, pwt.author_id, pwt.is_published, pwt.author_username, pwt.tools,
  ts_rank_cd((SELECT content_vector FROM posts WHERE id = pwt.id), websearch_to_tsquery('english', $1)) AS rank,
  COUNT(*) OVER() AS total_count,
  -- User status
  $4::boolean = true AND EXISTS(SELECT 1 FROM post_stars ps WHERE ps.post_id = pwt.id AND ps.liker_id = $5) AS is_starred
FROM posts_with_tools pwt
WHERE 
  websearch_to_tsquery('english', $1) @@ (SELECT content_vector FROM posts WHERE id = pwt.id) AND (($4::boolean = true AND pwt.author_id = $5) OR pwt.is_published)
ORDER BY 
  rank DESC
LIMIT $2 OFFSET $3
`

type SearchPostParams struct {
	WebsearchToTsquery string    `json:"websearch_to_tsquery"`
	Limit              int32     `json:"limit"`
	Offset             int32     `json:"offset"`
	IsAuthenticated    bool      `json:"is_authenticated"`
	AuthenticatedID    uuid.UUID `json:"authenticated_id"`
}

type SearchPostRow struct {
	ID              uuid.UUID          `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Description     string             `json:"description"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastDraftUpdate pgtype.Timestamptz `json:"last_draft_update"`
	LastPublish     pgtype.Timestamptz `json:"last_publish"`
	AuthorID        uuid.UUID          `json:"author_id"`
	IsPublished     pgtype.Bool        `json:"is_published"`
	AuthorUsername  string             `json:"author_username"`
	Tools           json.RawMessage    `json:"tools"`
	Rank            float32            `json:"rank"`
	TotalCount      int64              `json:"total_count"`
	IsStarred       pgtype.Bool        `json:"is_starred"`
}

func (q *Queries) SearchPost(ctx context.Context, arg SearchPostParams) ([]SearchPostRow, error) {
	rows, err := q.db.Query(ctx, searchPost,
		arg.WebsearchToTsquery,
		arg.Limit,
		arg.Offset,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostRow
	for rows.Next() {
		var i SearchPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.LastDraftUpdate,
			&i.LastPublish,
			&i.AuthorID,
			&i.IsPublished,
			&i.AuthorUsername,
			&i.Tools,
			&i.Rank,
			&i.TotalCount,
			&i.IsStarred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProfile = `-- name: SearchProfile :many
SELECT
  p.id,
  p.username,
  p.display_name,
  p.created_at,
  p.updated_at,
  ts_rank_cd(p.vector, websearch_to_tsquery('simple', $1)) AS rank,
  COUNT(*) OVER() AS total_count
FROM
  profiles p
WHERE
  websearch_to_tsquery('simple', $1) @@ p.vector
ORDER BY
  rank DESC
LIMIT $2 OFFSET $3
`

type SearchProfileParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
	Offset             int32  `json:"offset"`
}

type SearchProfileRow struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Rank        float32            `json:"rank"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) SearchProfile(ctx context.Context, arg SearchProfileParams) ([]SearchProfileRow, error) {
	rows, err := q.db.Query(ctx, searchProfile, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProfileRow
	for rows.Next() {
		var i SearchProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTool = `-- name: SearchTool :many
SELECT
  id, name, description, logo_url, created_at, updated_at, categories, vendor,
  $4::boolean = true AND EXISTS(SELECT 1 FROM stack_items si WHERE si.profile_id = $5 AND si.tool_id = twd.id) AS is_in_stack,
  $4::boolean = true AND EXISTS(SELECT 1 FROM watchlist_items wi WHERE wi.profile_id = $5 AND wi.tool_id = twd.id) AS is_in_watchlist,
  ts_rank_cd((SELECT vector FROM tools WHERE id = twd.id), websearch_to_tsquery('english', $1)) AS rank,
  COUNT(*) OVER() AS total_count
FROM tools_with_details twd
WHERE websearch_to_tsquery('english', $1) @@ (SELECT vector FROM tools WHERE id = twd.id)
ORDER BY rank DESC
LIMIT $2 OFFSET $3
`

type SearchToolParams struct {
	WebsearchToTsquery string    `json:"websearch_to_tsquery"`
	Limit              int32     `json:"limit"`
	Offset             int32     `json:"offset"`
	IsAuthenticated    bool      `json:"is_authenticated"`
	AuthenticatedID    uuid.UUID `json:"authenticated_id"`
}

type SearchToolRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Categories    interface{}        `json:"categories"`
	Vendor        json.RawMessage    `json:"vendor"`
	IsInStack     pgtype.Bool        `json:"is_in_stack"`
	IsInWatchlist pgtype.Bool        `json:"is_in_watchlist"`
	Rank          float32            `json:"rank"`
	TotalCount    int64              `json:"total_count"`
}

func (q *Queries) SearchTool(ctx context.Context, arg SearchToolParams) ([]SearchToolRow, error) {
	rows, err := q.db.Query(ctx, searchTool,
		arg.WebsearchToTsquery,
		arg.Limit,
		arg.Offset,
		arg.IsAuthenticated,
		arg.AuthenticatedID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchToolRow
	for rows.Next() {
		var i SearchToolRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Categories,
			&i.Vendor,
			&i.IsInStack,
			&i.IsInWatchlist,
			&i.Rank,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starPost = `-- name: StarPost :exec
INSERT INTO post_stars (
  post_id, liker_id
) VALUES (
  $1, $2
)
ON CONFLICT (post_id, liker_id) DO NOTHING
`

type StarPostParams struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) StarPost(ctx context.Context, arg StarPostParams) error {
	_, err := q.db.Exec(ctx, starPost, arg.PostID, arg.LikerID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const unpublishPost = `-- name: UnpublishPost :execrows
UPDATE posts
SET is_published = false, updated_at = now()
WHERE id = $1 AND author_id = $2
`

type UnpublishPostParams struct {
	ID       uuid.UUID `json:"id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) UnpublishPost(ctx context.Context, arg UnpublishPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpublishPost, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unstarPost = `-- name: UnstarPost :exec
DELETE FROM post_stars 
WHERE post_id = $1 
AND liker_id = $2
`

type UnstarPostParams struct {
	PostID  uuid.UUID `json:"post_id"`
	LikerID uuid.UUID `json:"liker_id"`
}

func (q *Queries) UnstarPost(ctx context.Context, arg UnstarPostParams) error {
	_, err := q.db.Exec(ctx, unstarPost, arg.PostID, arg.LikerID)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND author_id = $4
`

type UpdatePostParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	AuthorID    uuid.UUID `json:"author_id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AuthorID,
	)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET
  username = COALESCE($2, username),
  bio = COALESCE($3, bio),
  website = COALESCE($4, website),
  updated_at = now()
WHERE id = $1
`

type UpdateProfileParams struct {
	ID       uuid.UUID   `json:"id"`
	Username pgtype.Text `json:"username"`
	Bio      pgtype.Text `json:"bio"`
	Website  pgtype.Text `json:"website"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Username,
		arg.Bio,
		arg.Website,
	)
	return err
}
